### ISSUE TITLE
Optionally hide 'UpToDate' targets

### ISSUE THREAD

**Issue by jsvanbethlehem** [StefanKert/BuildVision#15]
It would be very helpful if the BuildVision output window could optionally hide all the 'UpToDate' projects. Currently, when working on large solutions, the stuff that is actually (incrementally) build becomes a bit hard to see between all the up-to-date targets.

Ideally this would be a checkbox on the BuildVision output pane, allowing switching between hiding/showing while a build is running. But it would also make sense maybe to make it a BuildVision option.

**Comment by mike03081972** [comment]
Hello,

This option will be very hopefull for me too :)

**Comment by StefanKert** [comment]
So just to elaborate this a bit let me start a discussion on this feature here. Any idea is really appreciated and I´d be really thankful to hear your thoughts on it.

From my point of view we have 3 different solutions on how to solve this. All of them could be combined, but especially 1 and 2 could be implemented together since this is already used for other settings.

### 1. Adding Option to BuildVision settings

This would result in adding another option to the settings menu. Pretty straight forward.

![image](https://user-images.githubusercontent.com/7176615/27468507-7d847a80-57ea-11e7-9187-a68a38cfc4a2.png)

### 2. Adding Item to Checkbox.

This would be similar to the **Show Header** Option that is currently available. You can either show up to date projects or not. 

![image](https://user-images.githubusercontent.com/7176615/27468463-493b990c-57ea-11e7-9404-58a48c779178.png)

### 3. Adding Checkbox to BuildVision Window 

Adding a Checkbox to the Mainwindow is also a possible solution, but since we´d really like to keep the window clean and tidy, I think we should take one of the other two options, but I am really open for feedback or arguments that support this one.


Looking forward to the discussion.

**Comment by TSchmiedlechner** [comment]
A combination of 1 and 2 would probably be the best solution, since the 'Show Header' option works the same way.

**Comment by StefanKert** [comment]
Hey guys,

I added this feature and really wanted to get some feedback on the colors and the visualization. I integrated a separate icon for up-to-date Projects and the count of up-to-date projects basically, this is a blue checkmark, but I am not really confident if this really is a good solution. Really love to hear your thoughts on it.

![image](https://user-images.githubusercontent.com/7176615/31573403-29a1ed06-b0bb-11e7-87f5-7d3db58f2076.png)

You can now hide projects via a context menu in the grid or through the settings dialog. There is just a little bug that I need to fix that currently leads to wrong alternate background colors. 

As I mentioned I really appreciate feedback on this. You can grab the version with the new functionality here: https://github.com/StefanKert/BuildVision/releases/tag/v2.1.0-alpha-3

Thanks in advance!

**Comment by JohnyWS** [comment]
Hmm, what about an outlined checkmark instead? Still green, giving the "all OK" feel, but empty to tell you that something is different? (sorta like these: https://www.shutterstock.com/image-vector/choose-mark-check-icon-red-green-578455546)

Love that I can better tell them apart now though!

**Comment by StefanKert** [comment]
@JohnyWS thanks for the feedback sir. 

![image](https://user-images.githubusercontent.com/7176615/31756067-2e5bae8c-b4a2-11e7-9a08-e08ca5a68344.png)

This are some ideas for icons that we can make us of (https://materialdesignicons.com/ for further possibilities).

IMO we have to use an icon that doesn´t distract the user too much. So in fact the really important icons are these:

**Comment by JohnyWS** [comment]
I like the double checkmark as well, but what does it convey? For me it is that "this node completed, as well as all child nodes". It then gets complicated if there's both up to date and regular built projects underneath, because what should the icon then be?

I think perhaps the following would do the job as to tell that something succeeded or not?

![error-and-resolved](https://user-images.githubusercontent.com/4435828/31819269-3cdc444e-b59c-11e7-8879-aaea55233bb0.png)

Just my 2 cents though. :)

**Comment by StefanKert** [comment]
Your right with your thoughts on the double checkmark. That was the reason why I didn´t use it in the first place. 

I don´t think that changing the current icons is a good thing because most users are really used to them. So we´ve to come up with a solution that matches the current icons. 

Since I am planning to release the newest version this weekend I think we should close this for now and wait for the feedback from further users and change it later on if it doesn´t work as expected. 

Anyway, I really wanted to thank you again for keeping up the discussion and for providing awesome feedback @JohnyWS !



So I am closing this for now, since there is no feedback. If this doesn´t work out for you, please reopen :)

@JohnyWS I will create a separate issue for UI discussions that fits the purpose of this discussion :)

cheers
