### ISSUE TITLE
New icon for build projects having warnings

### ISSUE THREAD

**Issue by muellerto** [StefanKert/BuildVision#42]
One thing I always missed is that warnings are not visualized by a colorful icon. In C++ there are a lot of warnings which have the importance of errors. The user should notice (and handle) them very seriously. But BuildVision gives him only a very tiny number in a column. You can easily overlook it. I would like to see a yellow icon instead of the green checkmark on the left side of each project which tells me "Hey, you have warnings! Look at them!".

**Comment by StefanKert** [comment]
Since this is the suggestions that most user will benefit from I will see if we can get this into the next release. 

So basically I think it is better to integrate this as Opt-Out so it is enabled per default and the user can disable it if someone likes the illusion of the green check mark better and ignore these errors ;)

In the end, it should look similar to this:

![image](https://user-images.githubusercontent.com/7176615/29446752-25eb8a0e-83ee-11e7-9eae-1053edd449c9.png)

Maybe someone got a better icon for this? Maybe you can add some thoughts @TSchmiedlechner?

**Comment by TSchmiedlechner** [comment]
Looks good! 👍 
I'd prefer sticking with the icons we currently use, because they are the same as in other places in VS (e.g. the error list).

**Comment by muellerto** [comment]
Looks great!

**Comment by StefanKert** [comment]
I added this feature with 369fa75.

You should now be able to see the builds that finish with a warning directly in BuildVision.

![image](https://user-images.githubusercontent.com/7176615/31034853-1bf671c8-a566-11e7-9ddd-640d0fa59683.png)

It is possible to disable this feature by going to your Generalsettings and check/uncheck the following option:

![image](https://user-images.githubusercontent.com/7176615/31034963-89f2d644-a566-11e7-9e7a-09d5d613f691.png)

I will push a new release asap, but in the meanwhile you can test this feature by installing the file you can finde [HERE](https://ci.appveyor.com/project/StefanKert/buildvision/build/2.0.1.111/artifacts)

Closing this for now. If something is wrong with this feature either open a new issue or reopen this one.
