### ISSUE TITLE
Can't Disable "Build Progress" Window

### ISSUE THREAD

**Issue by yannduran** [StefanKert/BuildVision#54]
- Visual Studio Version: 15.0.27130.2010
- BuildVision Version: 2.1.0.143 
- OS Version: Microsoft Windows NT 10.0.16299.0

**Steps to Reproduce:**

1. Start a build
2. Progress window opens

**Description:**

I can't seem to find a setting in any of the *BuildVision* settings tabs for this *'Build Progress'* window. The only setting that seems possibly related to it, called *'show indicators panel'*, has no effect on whether the window displays or not.

I've tried setting the window to *hide*, *auto-hide*, closed it etc, but the window always displays itself during the build. I don't need to see it, as I rely on the *BuildVision* tool window docked as a document to see the build progress.

It's very annoying to have this window appear during every build. Even more so due to the window's huge title. The image below shows what I see during **every** build (even with the window set to *auto-hide*).

![2017-12-23_14-24-06](https://user-images.githubusercontent.com/2031126/34316573-6467cb2c-e7ed-11e7-956b-98e5767dd7fc.png)

NB: The other windows show icons instead of titles because I have an extension installed to do that.

If the *'Build Progress"* window had an icon defined for it, it would also display the icon instead of the text. The *'Terminal Window'* window also has no icon defined.

**Comment by StefanKert** [comment]
Hey there,

thanks for the detailed description. Just to make sure that I am on the right track with this issue:

We are talking about this tab:

![image](https://user-images.githubusercontent.com/7176615/34421002-07e63586-ec0d-11e7-905e-dc76b8ac3746.png)

If so, this tab is added by CodeMaid (http://www.codemaid.net/documentation/#progressing) and since codemaid is opensource you can post your issue to their repo (https://github.com/codecadwallader/codemaid/issues)

**Comment by yannduran** [comment]
Uggh, thanks Stefan!I didn't even realise I had that installed. I'm sorry to have wasted your time.

**Comment by StefanKert** [comment]
No worries. Always glad to help :). Since we found the issue the time is not wasted!

**Comment by digital-spinner** [comment]
OMG, thank you for this one! I was started to pulling my hair out looking for the source of this bs.
