### ISSUE TITLE
Visual Studio 2019 Support

### ISSUE THREAD

**Issue by BoF-TiPa** [StefanKert/BuildVision#77]
I have used this tool for a long time. It is a great tool. When will it support Visual Studio 2019?

**Comment by StefanKert** [comment]
Hi @BoF-TiPa ,

since VS2019 requires the packages to support AsyncPackage I am currently working on migrating BuildVision (#71). 

Since there have been many changes I try to get as much feedback for the  preview as possible to don´t break users. If you have time check it out and let me know if it is working properly for you and if you have any suggestions:

The preview is hosted in the vsixgallery:  http://vsixgallery.com/extension/837c3c3b-8382-4839-9c9a-807b758a929f/

[This page](http://vsixgallery.com/guide/feed/) should give you a good overview on how you can subscribe :). If you have troubles using it let me know.

Thanks for your help.

**Comment by Chaosmeister** [comment]
Works fine for me

![image](https://user-images.githubusercontent.com/13346344/60032861-b90f4000-96a7-11e9-9834-ee250986bcf1.png)

**Comment by kubiix** [comment]
For me, when build s done, it still continues counting the time in BuildVision window and in VS statusbar.
Tried several project types - ASP.NET, WinForms, CoreConsole...

**Comment by tb-mtg** [comment]
Any progress on a non-preview version?

**Comment by rabauke** [comment]
Triggering compilation, it does not start until BuildVision window is hidden by switching to some other tab. Tested with 3.0.0.94 of Jul 5. 2019 16:46. This issue is observed with very large solutions only, not in general. I had installed also an earlier preview of the VS 2019 plugin (do not remember which version), which did not show this behavior.

**Comment by Ext3h** [comment]
SUffering from the same issue as @rabauke.

Tried to debug it, but unfortunately that preview build is missing about half the required PDB files. Any chance of providing an updated preview with the missing symbols added, so feedback can be provided?

**Comment by mtomana** [comment]
For me - the same issue at @rabauke and @Ext3h 
CPU is highly used, and it does nothing until you switch to other, for example, Output tab.

**Comment by StefanKert** [comment]
Hi folks,

sorry for the delay. I´ve been on a extended vacation this summer and had not much time to do OS stuff. 

@Ext3h I´ll take a look if I can bring up a build that includes those files. I´ll let you know as soon as it is deployd

Thanks for the tip with the CPU. I´ll check that. this might be related to #75.

**Comment by StefanKert** [comment]
Hi folks!

Finally I had time to get into some coding and I think i fixed most of the issues. Please checkout the newly pushed version (3.0.0-preview-1.96+2cf7960452) which should solve this issue. You should be able to update it if you configure VSIX Gallery in visual studio. 

Thanks in advance for the feedback! :)

**Comment by pyrocumulus** [comment]
I am currently testing this on my Visual Studio 2019. The basic functionality appears to be working correctly. 

How do you want to receive the feedback on this preview version? Through this issue or separate new issues? Because I think I've found a small bug.

**Comment by StefanKert** [comment]
If it is something unrelated to the current issue I would really appreciate if you could create another issue :)

**Comment by pyrocumulus** [comment]
Alright, it's a bit related I guess. But I submitted a separate issue #81 for your clarity :)

**Comment by toughengineer** [comment]
Hello.

When I open a solution (e.g. from explorer) BuildVision windows pops up in the middle of the screen while the solution is loading. Then it disappears when the solution is finished loading.

BuildVision window is docked at the bottom and is unpinned (the window is not shown, only tab is visible).

No big deal, but maybe it's easily fixable.

Otherwise it seems to work alright.

VS 2019 16.4.2.

**Comment by jzabroski** [comment]
I've noticed that too but assumed I did something.

**Comment by tb-mtg** [comment]
Version [3.0.0.99](http://vsixgallery.com/extension/837c3c3b-8382-4839-9c9a-807b758a929f/) appears to be working for me.  

Can you going to make it available on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=stefankert.BuildVision)?

**Comment by jzabroski** [comment]
Yeah, I havent observed any stability issues on VS 2019 16.4

**Comment by StefanKert** [comment]
BuidVision 3.0.0 is now available on the official Marketplace :) 
- Marketplace: https://marketplace.visualstudio.com/items?itemName=stefankert.BuildVision
- Release Notes: https://github.com/StefanKert/BuildVision/releases/tag/v3.0.0

Thanks to all of you for your help and your patience. I hope I can spend more time in the next few months to bring in additional Features.

Closing this now. Please create new issues if you are facing bugs in the latest version.
