### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by jzabroski** [StefanKert/BuildVision#83]
@nickcraver mentioned your tool on Twitter over the weekend [[1](https://twitter.com/Nick_Craver/status/1193163369299283968)] [[2](https://twitter.com/Nick_Craver/status/1193163889376141312)], and I had never heard of it before.  The performance issues he mentioned worry me, because we're moving to AWS Workspaces for all developer machines, and we know they're slightly slower than our current hardware.

Is there a good way to benchmark BuildVision and help improve its performance?  I imagine it might take me a couple of months to ramp up, but this tool seems worth it long-term as it's exactly what I've always wanted.

**Comment by NickCraver** [comment]
To be fair, my performance issues were many CI builds ago (and may not be issues now!) I'm going to poke it some more on latest and see. Visual Studio profiles extensions natively and will alert if there's a performance problem, so I wouldn't hesitate to test.

**Comment by jzabroski** [comment]
To be fair, I really want awesome development tools, and BuildVision is one of the few tools I really want.  The other is a concept I call "PackageLens" or CodeLens for Packages to eliminate a lot of the hard to reason about behavior of nuget packages that operate on the whole solution or project as a side-effect of installing them.  Sort of a visual "Scrap Your Boilerplate" for people familiar with the concept in Haskell, with the caveat that package authors would need to define some "type metadata" to allow PackageLens to not have a dirty lens to look through.

**Comment by StefanKert** [comment]
Hi there!

First of all thanks for offering help. It is greatly appreciated because it is sometimes hard to verify special cases that some users are facing (especially with very big solutions). 

Actually there are multiple ways do diagnose issues with performance. As @NickCraver mentioned VS2019 comes along with the notification for delaying extensions. I am not 100 percent sure if this is only related to UI hangs and startup performance or if it also detects performance issues when building things, because that was one of the major issues that have been fixed in the latest preview of BuildVision. 

The other profiling opportunity is to use [PerfView](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-diagnose-ui-delays-caused-by-extensions?view=vs-2019) which can sometimes be a bit tricky. 

I don´t know if there are any other blogposts, tools or docs on proper performance profling for extensions, but maybe @MadsKristensen knows if there is something new in this space. During the Meet-Up in Redmond in May this was one of the major points afaik that extension devs are missing. Maybe there is good news :)?

Beside those things:

Did you already give it a try? How big are the solutions that you are usually using? Because the real performance issues start >100 projects, so if you are working with that kind of solutions it would really help to get some insights.

**Comment by jzabroski** [comment]
I have not had any issues with up to 42 projects.
