### ISSUE TITLE
Build time beyond 1 hour

### ISSUE THREAD

**Issue by whazzup** [StefanKert/BuildVision#84]
Build times tabulated wrongly if total time is more than an hour.
Not major issue, but if it's a simple fix...
[https://i.imgur.com/XDXmYud.png](url)

**Comment by StefanKert** [comment]
Hi @whazzup,

just checked it with the latest bits and you should be able to just configure that in the Settings.

Tools -> Options -> BuildVision -> Build Messages 

![image](https://user-images.githubusercontent.com/7176615/87797362-dbdc3b80-c84a-11ea-9f41-2dc53ca3253e.png)

Instead of the default value which is `mm\:ss` you just put in `hh\:mm\:ss` :) that should show hours for the total time. This setting is also available for columns :).

I will close this issue since it should be resolved :) if not please reopen.
