### ISSUE TITLE
BuildVision window always shows when starting VS2019

### ISSUE THREAD

**Issue by PureKrome** [StefanKert/BuildVision#93]
When I start VS2019 by double clicking on _an existing `.sln` file` then BuildVision window _always_ shows in the top left corner of VS:

![image](https://user-images.githubusercontent.com/899878/79220311-18d51280-7e97-11ea-9b59-e07ae5d4cba7.png)

I've got it pinned to the bottom of VS (with other windows) and after VS completes loading up, it does disappear and is pinned to the bottom (correctly).

![image](https://user-images.githubusercontent.com/899878/79220484-6c476080-7e97-11ea-85c5-e59a5a7056f1.png)

No other window does this.

Would be really nice if this window remembers it's LAST STATE. In this case, the last state would be pinned to the bottom (with some other windows) and as such, wouldn't be showing when VS starts up.

**Comment by didierdonner** [comment]
Hello,

this happens also with Visual Studio 2017 15.9 too.

Regards,

Didier Donner

**Comment by StefanKert** [comment]
Hi folks!

Thanks for bringing this to my attention. This bug is currently per design, because we are not really able to load BuildVision before the Solution at the moment, at least I didn´t find a good option. Nevertheless I will try to find a workaround to fix this because I agree that this is really annoying.

**Comment by StefanKert** [comment]
This issue should be fixed with the upcoming version 3.0.1. :) BuildVision does behave similar to other extensions now and is hidden until it is properly loaded.
